### ISSUE TITLE
PackagesNotFoundError with installation.

### ISSUE THREAD

**Issue by chrissy005** [AstrobioMike/bit#27]
Hello, 

I get the following error as I try to install the package with Conda. Could you advise how I can proceed further.

conda create -n bit -c astrobiomike -c conda-forge -c bioconda -c defaults bit
Channels:
 - astrobiomike
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - bit

Current channels:

  - https://conda.anaconda.org/astrobiomike
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by chrissy005** [comment]
I think I managed to resolve this by specifying the platform flag in the command - "--platform osx-64" as the default platform is  osx-arm64

**Comment by AstrobioMike** [comment]
Heya, Chrissy :) 

Glad you sorted it out! But one point of clarification, that's not the default for any package (including bit), it's a default determined by your conda installation. The vast majority of things are still more likely to be found for the osx-64 architecture but not for the osx-arm64 one (including many of bit's dependencies). 

It's probably easiest to set your default to use osx-64, or install that version of conda rather than the osx-arm64 version (e.g., as recommended [here](https://astrobiomike.github.io/unix/conda-intro#getting-and-installing-conda)).
