### ISSUE TITLE
Feature request: download any accession

### ISSUE THREAD

**Issue by bkille** [AstrobioMike/bit#8]
Hi, would it be possible to add functionality for downloading _any_ accession ID? I'm trying to download some protein accessions at the moment, but the tool says they are not found. For example, AMR44288.1.

Thanks!

**Comment by AstrobioMike** [comment]
Hey there :)

I wrote the assembly download program when I needed it and couldn’t find anything else. But now since there exists a good dedicated program for downloading sequences by accession, called [ncbi-acc-download](https://github.com/kblin/ncbi-acc-download), I don’t know that I’ll add that functionality here. Maybe try that out and let me know if it doesn’t do what you are looking for? It’s also [conda installable](https://anaconda.org/bioconda/ncbi-acc-download)

**Comment by bkille** [comment]
Ahh that looks exactly like what I was looking for. Thanks!
