### ISSUE TITLE
taxid not found when using bit/bit-kraken2-to-taxon-summaries

### ISSUE THREAD

**Issue by laibinhuang** [AstrobioMike/bit#9]
lots of taxid not found when using bit/bit-kraken2-to-taxon-summaries, but when I check in NCBI, I find them, please help
21:30:19.605 [33m[WARN][0m taxid 2613770 was deleted
21:30:19.605 [33m[WARN][0m taxid 2843216 not found
21:30:19.605 [33m[WARN][0m taxid 2884264 not found
21:30:19.605 [33m[WARN][0m taxid 2782568 not found
21:30:19.605 [33m[WARN][0m taxid 2836373 not found
21:30:19.605 [33m[WARN][0m taxid 2842355 not found
21:30:19.605 [33m[WARN][0m taxid 2849779 not found
21:30:19.605 [33m[WARN][0m taxid 2789776 not found
21:30:19.605 [33m[WARN][0m taxid 2865832 not found
21:30:19.605 [33m[WARN][0m taxid 2884263 not found
21:30:19.605 [33m[WARN][0m taxid 2819238 not found
21:30:19.605 [33m[WARN][0m taxid 2781735 not found
21:30:19.605 [33m[WARN][0m taxid 2800788 not found

**Comment by AstrobioMike** [comment]
Hi there :)

Can you try running `bit-update-ncbi-taxonomy` in the bit conda environment? 

It may be that the stored NCBI taxonomy is older, and this should update it to current. Then see if the program correctly finds the ones you're seeing it can't find now but should be because they are active in the current NCBI taxonomy.

**Comment by laibinhuang** [comment]
Thank you very much, it works
